version: '3'

services:
  etcd:
    image: "quay.io/coreos/etcd:v3.3"
    container_name: "etcdv3.3"
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCDCTL_API: "3"
    volumes: 
      - $PWD/etcd/etcd0:/etcd_data
    ports:
      - 2379:2379
      - 2380:2380
      - 4001:4001
    networks:
      - dll-etcd-net
  etcd-manage:
    build: .
    volumes:
      - ./bin/config/cfg.toml:/app/config/cfg.toml
      - ./bin/logs:/app/logs
    ports:
      - "10280:10280"
    networks:
      - dll-etcd-net
networks:
  dll-etcd-net:
